unjs/consola

package.json, src/consola.js, src/index.js, test/custom-consola.test.js, yarn.lock
> fix: also assign consola to global
As consola was not assigned to the global scope by default, the 'require twice' test failed.
> feat: allow runtime set scope
If you want all consola statements, also in other modules, to use a scope you cannot use withScope as that returns a new consola instance. If you try to set that new consola instance to global then it doesnt work for all modules (both internal as external) that where already imported.
By adding this.scope to the Object.assign you can just override the scope by importing consola and then setting `consola.scope = 'my new scope'` during runtime. Eg in nuxt-generate-cluster I want to set the scope to eg 'worker 1' for the first worker etc. But without this feat I have to set the scope in each of my modules again, and then still the …
=> add a fix, a feature and a test

package.json
Hi,
I saw you had typescript typings, but they never got shipped with the package nor exposed.
=> fix: expose typescript typings

types/consola.d.ts
Consola supports logging for all types. Updates typings to allow `message` to be of type `any`.
Closes #38
=> fix(ts): set message type to "any"

types/consola.d.ts
I got some errors regarding "noImplicitAny" rule when building with TypeScript.
To solve this problem, I modified to add `any` type to several definition explicitly.
```
2:11 Parameter 'logObj' implicitly has an 'any' type.
1 | declare interface ConsolaReporter {
> 2 |     log: (logObj, { async, stdout, stderr }) => void
|           ^
3 | }
4 |
5 | declare class Consola {
2:21 Binding element 'async' implicitly has an 'any' type.
1 | declare interface ConsolaReporter {
> 2 |     log: (logObj, { async, stdout, stderr }) => void
|                     ^
3 | }
4 |
5 | declare class Consola {
2:28 Binding element 'stdout' implicitly has an 'any' type.
1 | declare interface ConsolaReporter {
> 2 |     log: (logObj, { async, stdout, stderr }) => void
|                            ^
3 | }
4 |
5 | …
```
=> fix(ts): set type "any" explicitly

types/consola.d.ts
In order to be able to use the Consola class as a type outside of this project, its declarations must be exported.
=> fix(ts): export consola ts declarations

types/consola.d.ts
It appears this broke the consola declarations altogether. 😓
I'll do a little more testing locally before creating another PR fixing the declarations.
Sorry about that.
=> fix(ts): revert export consola ts declarations

types/consola.d.ts
Adapted all log functions to have the same signature as console.log
Also reindented the whole thing with 2 spaces (as the rest of the
project)
tell me if you want the previous style back (I pretty much automatically formatted the file)
=> fix(types): allow passing extra arguments

src/reporters/browser.js
=> fix(browser): use `console.warn` when possible

types/consola.d.ts
Hi,
Currently typescript type definitions are too loosely typed and lacks many informations. I propose the followings typings to enhance autocompletion usage and also to provide interfaces to help typing configuration objects.
Every interface is exported so we can extend them when building custom reporters. I removed the module declaration since the `types` field of the `package.json` for `consola` already points to the type declaration file.
Also moved from all static class to instantiated class since it's more accurate with the way Consola really works.
I did not wrote the type definitions for all the reporters as I don't know if it's needed or not. Let me know if you want me to add it.
Thanks for your work,
Ben
=> feat: improve typescript type definitions

types/consola.d.ts
The current Typescript declaration file have some missing properties.
=> fix: add missing typescript declaration for level, stdout and stderr

src/reporters/browser.js
Hi,
Currently Consola does not support the usage of formatted strings with the `BrowserReporter`. Example, if you log with the following arguments:
```js
logger.error('Error: %s is not a valid configuration key', 'test')
```
It will output:
```
Error: %s is not a valid configuration key test
```
Instead of:
```
Error: test is not a valid configuration key
```
So in this PR, i made a small modification to add the support for this functionality.
Thanks
=> feat(browser): add support of formatted strings

types/consola.d.ts
Fix a typing issue that causes this to throw a typing error on `consola.green`:
```js
// @ts-check
const consola = require('consola')
consola.green('foo')
```
=> fix(types): const consola = require('consola') type is wrong

src/index.js, src/logLevels.js, src/types.js, types/consola.d.ts
=> feat(types): add missing typescript definitions for reporters

package.json, src/browser.js, src/node.js
=> fix: new LogLevel enum is not exported properly #95

src/reporters/basic.js, src/reporters/fancy.js
If `formatOptions.date` is `false`, the date won't show. (Screenshot out of date)
Defaults to `true` (same as current behavior).
Closes https://cmty.app/nuxt/consola/issues/c75
=> feat: support `formatOptions.date` to optionally hide date

types/consola.d.ts
This makes the possible values of type specifically defined, so you can
handle them more safely.
=> feat(types): use union type for `ConsolaLogObject.type`

src/browser.js, src/types.js
Hey,
I wanted to test out consola quickly, cloned the repo and draw up an nginx. 
Initially the example `/examples/index.html` wasn't working as the file `logLevel` coulnd't be found (Accessing via browser console).
For me the fix was to add `.js` when importing the file.
I fixed the issue with this pr.
=> chore: make example/index.js working

LICENSE, README.md, examples/prompt.ts, package.json, pnpm-lock.yaml, src/consola.ts, src/index.browser.ts, src/index.shared.ts, src/index.ts, src/prompt.ts, src/types.ts, src/utils/prompt.ts
Closes #169
Add support for `await consola.prompt` based on `@clak/core` and a themed version of `@clak/prompts`.
Browser build uses native `prompt`/`confirm`
=> feat: `consola.prompt` util

README.md
This PR fixes file links in `README.md` to point to `.ts` files instead of `.js`.
=> docs: fix links to the source files

README.md, basic.d.ts.ts, browser.d.ts.ts, core.d.ts, package.json, src/consola.ts, src/index.basic.ts, src/index.core.ts
Base build without fancy reporter, saves ~80% of the bundle size.
=> feat: `/basic`, `/core` and `/browser` subpath exports

README.md, examples/special.ts, src/reporters/fancy.ts
Similar to highlighting backticks, this adds functionality to underline.
Renamed `highlightBackticks` to `characterFormat` to chain the formatting. 🙂 
Preview (based on `examples/special.ts`):
Update: added special format syntax as well (really need this feature!)
=> feat(fancy): underlining

src/consola.ts
=> fix: preserve tag casing

LICENSE, README.md, package.json, pnpm-lock.yaml, src/reporters/fancy.ts, src/utils.ts, src/utils/box.ts, src/utils/color.ts, src/utils/prompt.ts
Export color utils from `consola/utils` subpath:
- `colors[name]`
- `getColor(name)`
- `colorize(name, text)`
Implementation is based on [colorette](https://github.com/jorgebucaran/colorette) which was already being used to make some small tweaks and generate types from the source. (Thanks @jorgebucaran and contribs for this amazing lib ❤️ )
Also thanks @antfu for original idea in #166
=> feat: color utils

src/utils/box.ts
@pi0 the naming seemed to be off so I just wanted to make a simple PR to fix it. 
Thanks,
CP 🚀
=> fix(box): fix preset naming for `singleThick`

examples/spinner.ts
`start` or `success` does not return a promise.
=> chore: remove extra `await` in `spinner` example

src/utils/box.ts
Implementation already supports partial options
=> fix(types): partial style options for `box`

.github/workflows/autofix.yml
=> ci: use conventional commit for autofix

examples/prompt.ts, src/prompt.ts, src/utils/prompt.ts
`SelectPrompt` and `MultiSelectPrompt` of `@clack/core` support `initialValue` option. In [utils](https://github.com/unjs/consola/blob/main/src/utils/prompt.ts) file this option is used, but in [prompt](https://github.com/unjs/consola/blob/main/src/prompt.ts) file `initial` option is not passed to `initialValue`/`initialValues` options
This pull request fixes that problem
=> fix: use `initial` in `select` and `multiselect` prompts

README.md
Actually not 100% sure since I cannot mock right, happy to get help on this too
=> docs: add vitest

README.md, examples/raw.ts
Closes #268 
Add a chapter about the raw function to bypass potential bad interpretation from reporter.
=> docs: add docs about raw method

src/utils/box.ts, src/utils/color.ts, src/utils/error.ts, src/utils/format.ts, src/utils/log.ts, src/utils/prompt.ts, src/utils/stream.ts, src/utils/string.ts, src/utils/tree.ts
I needed to use some function from `color.ts` for the terminal cli I'm doing, so I decided to add the missing jsdocs for the `utils` folder. The rest of the jsdocs for the missing functions will be part of another PR unless you think should be part of this PR.
> Any feedback is welcomed! 🙌
=> docs: add jsdocs for utils functions

src/basic.ts, src/browser.ts, src/consola.ts, src/constants.ts, src/index.ts, src/prompt.ts, src/types.ts
Added JSDocs to top level functions. This is a continuation work from #286.
> Any feedback is welcomed! 🙌
=> docs: add jsdocs for top-level functions

examples/error.ts, src/reporters/basic.ts, src/reporters/fancy.ts, src/types.ts
The `cause` property of Error had been support in [most runtime](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause#browser_compatibility) and been widely adapted by many repo.
The Chrome devtool already support showing caused error like screenshot below ⬇️
This PR support report error cause to console while used in node. Related issue #202 
Test code provided:
```ts
import { consola } from "./src/index";
consola.error(
new Error("This is an error", {
cause: new Error("This is the cause", {
cause: new Error("This is the cause of the cause"),
}),
}),
);
```
=> feat: support report error `cause`

README.md, src/prompt.ts
Resolves #234 #251
When prompts get canceled by user Ctrl+C it was returning (untyped/undocumented) `Symbol(clack:cancel)`.
This PR adds a new `cancel` option to specify strategy:
- `"default"` - Resolve the promise with the `default` value or `initial` value.
- `"undefined`" - Resolve the promise with `undefined`.
- `"null"` - Resolve the promise with `null`.
- `"symbol"` - Resolve the promise with a symbol `Symbol.for("cancel")`.
- `"reject"` - Reject the promise with an error.
Default is set to `"default"` a small behavior change from current that returns the internal Clack symbol to keep backward compatibility with (expected) typed behavior.
Possible canceled return type is added
=> feat(prompt): configurable cancel strategy

src/reporters/fancy.ts
Added a fallback to handle cases where Intl isn’t available. This keeps things running smoothly even in environments without Intl support. For more details, check out the [Node.js docs on detecting internationalization support](https://nodejs.org/api/intl.html#detecting-internationalization-support).
=> fix(fancy): fallback when`Intl` is unavailable

package.json
resolves #324
add nested export conditions to be more friendly with typescript node16 resolution and use explicit cjs/mjs extensions.
this change was introduced in https://github.com/unjs/consola/commit/18bc852 / 3.3.2 which caused a regression (#329) because of backward compatibility of libraries that depend on cjs + default export of consola (https://github.com/unjs/consola/pull/331/commits/952b961d3eb51deb6c65b22348d138fb44b7bf79 fixes it by using [compat entry](https://github.com/unjs/consola/blob/main/lib/index.cjs) for `exports.node.require.default` condition.
=>  build: update exports for node16 typescript resolution

examples/box.ts, src/utils/box.ts
=> fix: calculate box width without escape sequence chars

examples/error.ts, src/reporters/basic.ts, src/reporters/fancy.ts, src/utils/error.ts
Resolves #355
If an error message contains multiple lines, we need to count them and remove them from the beginning of the stack (previously we was assumed to drop hardcoded number of `1` lines)
=> fix: remove all message lines from stack
